import { App, PluginSettingTab, Setting } from 'obsidian'
import type WeChatPreviewPlugin from '../main'
import { themes } from '../core/themes'

export type WeChatPreviewSettings = {
  themeName: string
  metaText: string
  footerText: string
  openRouterApiKey: string
  openRouterModel: string
  autoGenerateEnabled: boolean
  autoGenerateDebounceMs: number
}

export const DEFAULT_SETTINGS: WeChatPreviewSettings = {
  themeName: 'klein',
  metaText: 'BUBBLE · 2026 · UPDATE.03',
  footerText: 'BUBBLE / DESIGN',
  openRouterApiKey: '',
  openRouterModel: 'google/gemini-3.1-pro-preview',
  autoGenerateEnabled: false,
  autoGenerateDebounceMs: 1500,
}

export class WeChatPreviewSettingTab extends PluginSettingTab {
  private plugin: WeChatPreviewPlugin

  constructor(app: App, plugin: WeChatPreviewPlugin) {
    super(app, plugin)
    this.plugin = plugin
  }

  display(): void {
    const { containerEl } = this
    containerEl.empty()

    containerEl.createEl('h2', { text: 'WeChat Preview' })
    containerEl.createEl('h3', { text: 'OpenRouter (AI HTML generation)' })

    new Setting(containerEl)
      .setName('OpenRouter API Key')
      .setDesc('Used to generate HTML via OpenRouter. Stored in local plugin settings.')
      .addText((text) => {
        text.inputEl.type = 'password'
        text.setPlaceholder('sk-or-v1-...')
        text.setValue(this.plugin.settings.openRouterApiKey)
        text.onChange(async (value) => {
          this.plugin.settings.openRouterApiKey = value.trim()
          await this.plugin.saveSettings()
        })
      })

    new Setting(containerEl)
      .setName('Model')
      .setDesc('OpenRouter model id.')
      .addText((text) => {
        text.setPlaceholder('google/gemini-3.1-pro-preview')
        text.setValue(this.plugin.settings.openRouterModel)
        text.onChange(async (value) => {
          this.plugin.settings.openRouterModel = value.trim()
          await this.plugin.saveSettings()
        })
      })

    new Setting(containerEl)
      .setName('Auto-generate AI HTML')
      .setDesc('Trigger on note edit (debounce) and note switch.')
      .addToggle((toggle) => {
        toggle.setValue(this.plugin.settings.autoGenerateEnabled)
        toggle.onChange(async (value) => {
          this.plugin.settings.autoGenerateEnabled = value
          await this.plugin.saveSettings()
        })
      })

    new Setting(containerEl).setName('Auto-generate behavior').setDesc(
      `Debounce is fixed at ${this.plugin.settings.autoGenerateDebounceMs}ms; note switch also triggers generation.`,
    )

    containerEl.createEl('h3', { text: 'Local fallback rendering (used when AI is unavailable)' })

    new Setting(containerEl)
      .setName('Theme')
      .setDesc('Theme for local fallback preview/export.')
      .addDropdown((dropdown) => {
        themes.forEach((t) => dropdown.addOption(t.name, t.label))
        dropdown.setValue(this.plugin.settings.themeName)
        dropdown.onChange(async (value) => {
          this.plugin.settings.themeName = value
          await this.plugin.saveSettings()
        })
      })

    new Setting(containerEl)
      .setName('Swiss Klein meta header')
      .setDesc('Top label text used by local fallback rendering.')
      .addText((text) => {
        text.setPlaceholder('BUBBLE · 2026 · UPDATE.03')
        text.setValue(this.plugin.settings.metaText)
        text.onChange(async (value) => {
          this.plugin.settings.metaText = value
          await this.plugin.saveSettings()
        })
      })

    new Setting(containerEl)
      .setName('Swiss Klein footer')
      .setDesc('Bottom signature used by local fallback rendering.')
      .addText((text) => {
        text.setPlaceholder('BUBBLE / DESIGN')
        text.setValue(this.plugin.settings.footerText)
        text.onChange(async (value) => {
          this.plugin.settings.footerText = value
          await this.plugin.saveSettings()
        })
      })
  }
}
