import { App, PluginSettingTab, Setting } from 'obsidian'
import type WeChatPreviewPlugin from '../main'
import { promptThemes } from '../core/aiPrompts'

export type WeChatPreviewSettings = {
  openRouterApiKey: string
  openRouterModel: string
  promptThemeId: string
  autoGenerateEnabled: boolean
  autoGenerateDebounceMs: number
}

export const DEFAULT_SETTINGS: WeChatPreviewSettings = {
  openRouterApiKey: '',
  openRouterModel: 'google/gemini-3.1-pro-preview',
  promptThemeId: 'digital-tool-guide',
  autoGenerateEnabled: false,
  autoGenerateDebounceMs: 1500,
}

export class WeChatPreviewSettingTab extends PluginSettingTab {
  private plugin: WeChatPreviewPlugin

  constructor(app: App, plugin: WeChatPreviewPlugin) {
    super(app, plugin)
    this.plugin = plugin
  }

  display(): void {
    const { containerEl } = this
    containerEl.empty()

    containerEl.createEl('h2', { text: 'WeChat Preview' })

    new Setting(containerEl)
      .setName('OpenRouter API Key')
      .setDesc('Used to generate HTML via OpenRouter. Stored in local plugin settings.')
      .addText((text) => {
        text.inputEl.type = 'password'
        text.setPlaceholder('sk-or-v1-...')
        text.setValue(this.plugin.settings.openRouterApiKey)
        text.onChange(async (value) => {
          this.plugin.settings.openRouterApiKey = value.trim()
          await this.plugin.saveSettings()
        })
      })

    new Setting(containerEl)
      .setName('Model')
      .setDesc('OpenRouter model id.')
      .addText((text) => {
        text.setPlaceholder('google/gemini-3.1-pro-preview')
        text.setValue(this.plugin.settings.openRouterModel)
        text.onChange(async (value) => {
          this.plugin.settings.openRouterModel = value.trim()
          await this.plugin.saveSettings()
        })
      })

    new Setting(containerEl)
      .setName('主题')
      .setDesc('控制发送给模型的排版主题提示词，后续可扩展更多主题。')
      .addDropdown((dropdown) => {
        promptThemes.forEach((theme) => dropdown.addOption(theme.id, theme.label))
        dropdown.setValue(this.plugin.settings.promptThemeId)
        dropdown.onChange(async (value) => {
          this.plugin.settings.promptThemeId = value
          await this.plugin.saveSettings()
        })
      })

    new Setting(containerEl)
      .setName('Auto-generate AI HTML')
      .setDesc('Trigger on note edit (debounce) and note switch.')
      .addToggle((toggle) => {
        toggle.setValue(this.plugin.settings.autoGenerateEnabled)
        toggle.onChange(async (value) => {
          this.plugin.settings.autoGenerateEnabled = value
          await this.plugin.saveSettings()
        })
      })

    new Setting(containerEl)
      .setName('Auto-generate behavior')
      .setDesc(
        `Debounce is fixed at ${this.plugin.settings.autoGenerateDebounceMs}ms, and note switch also triggers generation.`,
      )
  }
}
